apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: sa-researcher
      containers:
        - name: backend
          image: jjyoung22/ztcbackend:poc
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: "w2-k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
